#ifndef __LINEAR_ACTUATOR_H__
#define __LINEAR_ACTUATOR_H__

#include "gd32f30x.h"

#define INTERFACE1_TIPPING_MOTOR_CTL_PORT1 				GPIOC
#define INTERFACE1_TIPPING_MOTOR_CTL_PIN1             	GPIO_PIN_1
#define INTERFACE1_TIPPING_MOTOR_CTL_PORT2 				GPIOC
#define INTERFACE1_TIPPING_MOTOR_CTL_PIN2             	GPIO_PIN_0
#define INTERFACE1_TIPPING_MOTOR_CTL1_PORT_RCU         	RCU_GPIOC
#define INTERFACE1_TIPPING_MOTOR_CTL2_PORT_RCU        	RCU_GPIOC

#define INTERFACE1_DOOR_MOTOR_CTL_PORT1 				GPIOC
#define INTERFACE1_DOOR_MOTOR_CTL_PIN1           		GPIO_PIN_3
#define INTERFACE1_DOOR_MOTOR_CTL_PORT2 				GPIOC
#define INTERFACE1_DOOR_MOTOR_CTL_PIN2           		GPIO_PIN_2
#define INTERFACE1_DOOR_MOTOR_CTL1_PORT_RCU      		RCU_GPIOC
#define INTERFACE1_DOOR_MOTOR_CTL2_PORT_RCU      		RCU_GPIOC

#define INTERFACE2_TIPPING_MOTOR_CTL_PORT1 				GPIOE
#define INTERFACE2_TIPPING_MOTOR_CTL_PIN1              	GPIO_PIN_5
#define INTERFACE2_TIPPING_MOTOR_CTL_PORT2 				GPIOE
#define INTERFACE2_TIPPING_MOTOR_CTL_PIN2             	GPIO_PIN_4
#define INTERFACE2_TIPPING_MOTOR_CTL1_PORT_RCU         	RCU_GPIOE
#define INTERFACE2_TIPPING_MOTOR_CTL2_PORT_RCU        	RCU_GPIOE

#define INTERFACE2_DOOR_MOTOR_CTL_PORT1 				GPIOC
#define INTERFACE2_DOOR_MOTOR_CTL_PIN1           		GPIO_PIN_13
#define INTERFACE2_DOOR_MOTOR_CTL_PORT2 				GPIOE
#define INTERFACE2_DOOR_MOTOR_CTL_PIN2           		GPIO_PIN_6
#define INTERFACE2_DOOR_MOTOR_CTL1_PORT_RCU      		RCU_GPIOC
#define INTERFACE2_DOOR_MOTOR_CTL2_PORT_RCU      		RCU_GPIOE

#define INTERFACE3_TIPPING_MOTOR_CTL_PORT1 				GPIOB
#define INTERFACE3_TIPPING_MOTOR_CTL_PIN1              	GPIO_PIN_9
#define INTERFACE3_TIPPING_MOTOR_CTL_PORT2 				GPIOB
#define INTERFACE3_TIPPING_MOTOR_CTL_PIN2             	GPIO_PIN_8
#define INTERFACE3_TIPPING_MOTOR_CTL1_PORT_RCU         	RCU_GPIOD
#define INTERFACE3_TIPPING_MOTOR_CTL2_PORT_RCU        	RCU_GPIOD

#define INTERFACE3_DOOR_MOTOR_CTL_PORT1 				GPIOE
#define INTERFACE3_DOOR_MOTOR_CTL_PIN1           		GPIO_PIN_1
#define INTERFACE3_DOOR_MOTOR_CTL_PORT2 				GPIOE
#define INTERFACE3_DOOR_MOTOR_CTL_PIN2          	 	GPIO_PIN_0
#define INTERFACE3_DOOR_MOTOR_CTL1_PORT_RCU      		RCU_GPIOE
#define INTERFACE3_DOOR_MOTOR_CTL2_PORT_RCU      		RCU_GPIOE

#define INTERFACE4_TIPPING_MOTOR_CTL_PORT1 				GPIOC
#define INTERFACE4_TIPPING_MOTOR_CTL_PIN1              	GPIO_PIN_8
#define INTERFACE4_TIPPING_MOTOR_CTL_PORT2 				GPIOC
#define INTERFACE4_TIPPING_MOTOR_CTL_PIN2             	GPIO_PIN_7
#define INTERFACE4_TIPPING_MOTOR_CTL1_PORT_RCU         	RCU_GPIOC
#define INTERFACE4_TIPPING_MOTOR_CTL2_PORT_RCU        	RCU_GPIOC

#define INTERFACE4_DOOR_MOTOR_CTL_PORT1 				GPIOA
#define INTERFACE4_DOOR_MOTOR_CTL_PIN1           		GPIO_PIN_8
#define INTERFACE4_DOOR_MOTOR_CTL_PORT2 				GPIOC
#define INTERFACE4_DOOR_MOTOR_CTL_PIN2          	 	GPIO_PIN_9
#define INTERFACE4_DOOR_MOTOR_CTL1_PORT_RCU      		RCU_GPIOA
#define INTERFACE4_DOOR_MOTOR_CTL2_PORT_RCU      		RCU_GPIOC

#define INTERFACE5_TIPPING_MOTOR_CTL_PORT1 				GPIOD
#define INTERFACE5_TIPPING_MOTOR_CTL_PIN1              	GPIO_PIN_12
#define INTERFACE5_TIPPING_MOTOR_CTL_PORT2 				GPIOD
#define INTERFACE5_TIPPING_MOTOR_CTL_PIN2             	GPIO_PIN_11
#define INTERFACE5_TIPPING_MOTOR_CTL1_PORT_RCU         	RCU_GPIOD
#define INTERFACE5_TIPPING_MOTOR_CTL2_PORT_RCU        	RCU_GPIOD

#define INTERFACE5_DOOR_MOTOR_CTL_PORT1 				GPIOD
#define INTERFACE5_DOOR_MOTOR_CTL_PIN1           		GPIO_PIN_14
#define INTERFACE5_DOOR_MOTOR_CTL_PORT2 				GPIOD
#define INTERFACE5_DOOR_MOTOR_CTL_PIN2          	 	GPIO_PIN_13
#define INTERFACE5_DOOR_MOTOR_CTL1_PORT_RCU      		RCU_GPIOD
#define INTERFACE5_DOOR_MOTOR_CTL2_PORT_RCU      		RCU_GPIOD

#define INTERFACE6_TIPPING_MOTOR_CTL_PORT1 				GPIOB
#define INTERFACE6_TIPPING_MOTOR_CTL_PIN1              	GPIO_PIN_14
#define INTERFACE6_TIPPING_MOTOR_CTL_PORT2 				GPIOB
#define INTERFACE6_TIPPING_MOTOR_CTL_PIN2             	GPIO_PIN_13
#define INTERFACE6_TIPPING_MOTOR_CTL1_PORT_RCU         	RCU_GPIOB
#define INTERFACE6_TIPPING_MOTOR_CTL2_PORT_RCU        	RCU_GPIOB

#define INTERFACE6_DOOR_MOTOR_CTL_PORT1 				GPIOD
#define INTERFACE6_DOOR_MOTOR_CTL_PIN1           		GPIO_PIN_8
#define INTERFACE6_DOOR_MOTOR_CTL_PORT2 				GPIOB
#define INTERFACE6_DOOR_MOTOR_CTL_PIN2          	 	GPIO_PIN_15
#define INTERFACE6_DOOR_MOTOR_CTL1_PORT_RCU      		RCU_GPIOD
#define INTERFACE6_DOOR_MOTOR_CTL2_PORT_RCU      		RCU_GPIOB

enum linear_actuator_state_enum_t{
	LA_CLOSE,
	LA_OPEN,
	LA_STOP
};

struct linear_actuator_hw_info_t {
	uint32_t 			ctl1_gpio;
	uint32_t 			ctl1_pin;
	rcu_periph_enum 	ctl1_gpio_rcu;
	uint32_t 			ctl2_gpio;
	uint32_t 			ctl2_pin;
	rcu_periph_enum 	ctl2_gpio_rcu;
};

typedef struct linear_actuator_ {
	struct linear_actuator_hw_info_t 	hw_info;
	enum linear_actuator_state_enum_t 	state;
}linear_actuator_t;

int linear_actuator_init(linear_actuator_t *);
void linear_actuator_ctl(linear_actuator_t *, enum linear_actuator_state_enum_t);

#endif
